language: python
services:
  - docker
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to install dependencies
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
#  - docker build -t squad42/imageComments .
#  - sudo docker run -d -p5002:5002 squad42/imageComments
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python -m pytest
